dependencies:
  # - <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    remappings:
     - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
